### ISSUE TITLE
Anchors on help page broken

### ISSUE THREAD

**Issue by Freakspot** [DevWars/dev-wars#15]
http://devwars.tv/help
When clicking on an anchor, I seem to get taken to a wrong site: http://devwars.tv/ **dashboard** #ah4.
Using Windows 10 & newest Version of Chrome.

**Comment by crai9** [comment]
Can't seem replicate this on Windows 10 and Chrome 45 :worried:

**Comment by Freakspot** [comment]
Just tried it out again, seems to be working fine now. Weird.
